var time = $.getJSON("./time.json"),
    timee = [],
    ith = [];
var price = $.getJSON("./price.json"),
    pcicee = [],
    nth = [];
var station = $.getJSON("./station.json"),
    stationn = [],
    kth = [];
var statCnt = 20,
    ini = 0;